project_id = "imrxzkivwrkqbhqfbbes"

[functions.generate-cast-content]
verify_jwt = true

[functions.customer-chat]
verify_jwt = false

[functions.generate-sms-message]
verify_jwt = true

[functions.sync-website-photos]
verify_jwt = true



[functions.auto-therapist-intro]
verify_jwt = false

[functions.notify-line-booking]
verify_jwt = false

